apiVersion: v1
kind: Namespace
metadata:
  name: develop

---
# backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: xicoxavier/back-develop
        
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: develop
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-develop
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: api.10.49.10.42.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

---
# frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-develop
  namespace: develop
  labels:
    app: front-end-develop
spec:
  selector:
    matchLabels:
      app: front-end-develop
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end-develop
    spec:
      containers:
       - name: nginx
         image: xicoxavier/front-develop
         ports:
         - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front-end-clusterip-develop
  namespace: develop
spec:
  type: ClusterIP
  selector:
    app: front-end-develop
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-primario-develop
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: develop.10.49.10.42.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end-clusterip-develop
            port:
              number: 80